### ISSUE TITLE
What's the usage of type (t) in configuration

### ISSUE THREAD

**Issue by ronisegoly** [hamishcunningham/pi-tronics#100]
There are several options, does it change the behaviour of the Mopi? Or in any case the highter voltage will be used

Where t (type) is 1 for rechargeable batteries, 2 for non-rechargeable
    batteries, 3 for PSU / DC adapter,

**Comment by hamishcunningham** [comment]
This section of the manual gives detail of what happens with different chemistries / PSU types: https://pi.gate.ac.uk/pages/mopi.html#config-ui

But always the highest voltage supply will be used.
