### ISSUE TITLE
Mopi & RPi with touchscreen

### ISSUE THREAD

**Issue by Boki85** [hamishcunningham/pi-tronics#101]
Hello
I would like to set up an RPi 2B with the 7'' Touch Screen LCD (http://uk.rs-online.com/web/p/graphics-display-development-kits/8997466/), in combination with the Mopi.
I managed to configure the Mopi correctly, but I am looking for a solution how to supply the Pi Adapter board for the LCD screen by the Mopi when the main power (micro USB of the RPi) gets switched off.
My main purpose is to use the Mopi with its batteries as a UPS when the main power gets lost. This actually works fine for the RPi it self, but my screen has no power supply from that moment on.
I have a low profile model of Mopi. So my issue is how to provide the 5V to the adapter board when thr Rpi is supplied by the Mopi / in battery mode.
I can use a wire for GND from the remaining GPIO PINs, but I have no access to the 5V PINs as Mopi is connected.
Thanks for your suggestions.

**Comment by hamishcunningham** [comment]
Not sure I totally understand, but perhaps you need a circuit like this one? https://www.circuitlab.com/circuit/wk2g43/mopi-high-current/

Re. getting at the 5V when you're using a low-profile MoPi, you'll need to solder onto one of the 5V rails I think.
