### ISSUE TITLE
I was hoping to enjoy this product

### ISSUE THREAD

**Issue by ronisegoly** [hamishcunningham/pi-tronics#102]
But I am left with open questions and no answers and need to look for solution elsewhere

**Comment by hamishcunningham** [comment]
my apologies, I have been very busy and then it was xmas and...

I should be able to get to your open issues on Sunday

in the meantime one thing you could try is searching the closed issues, some of which may duplicate the questions you have asked?

all the best

hamish

**Comment by ronisegoly** [comment]
I understand the pressure I just assumed the product is done and ready. I will wait a bit
