### ISSUE TITLE
timer-based wake-up

### ISSUE THREAD

**Issue by crottolo** [hamishcunningham/pi-tronics#111]
Hi, 
have you the documentation for wake-up start and stop for mopi?

i want schedule time based start for day of the week.
same as http://www.uugear.com/app/wittypi-scriptgen/

thanks

**Comment by hamishcunningham** [comment]
https://pi.gate.ac.uk/pages/mopi.html#section-4.3.

**Comment by crottolo** [comment]
Thanks for answer.
Is possible set days (monday to friday) from 8.00am to 18.00pm?

I want the scheduler for on off.

If possible store the Configuration for start and stop rpi?

Thanks 

Inviato da iPhone

> Il giorno 30 gen 2018, alle ore 21:20, Hamish Cunningham <notifications@github.com> ha scritto:
> 
> https://pi.gate.ac.uk/pages/mopi.html#section-4.3.
> 
> 
>

**Comment by petaflot** [comment]
not sure there's an RTC on the MoPi.

IMHO you should you a crontab entry to set the next power-on event (same thing for power-off)
