### ISSUE TITLE
Cannot install simbamond on Ubuntu MATE 18

### ISSUE THREAD

**Issue by aaronpatty** [hamishcunningham/pi-tronics#114]
I have a similar issue to [Issue 110](https://github.com/hamishcunningham/pi-tronics/issues/110).. I get an "Unable to locate package simbamond" when trying to install on Ubuntu MATE release 18.04.2 LTS 32-Bit (MATE 1.20.1) on my Pi 3 B+.  What can I do to get this installed?

Thanks!

**Comment by hamishcunningham** [comment]
hi, simbamond is a package in raspbian, so not available by default in other distros. if you google "install raspbian package on ubuntu" you should find relevant stuff, including https://www.raspberrypi.org/forums/viewtopic.php?t=27915
hth, h
