### ISSUE TITLE
Mopi 2 Py Zero W

### ISSUE THREAD

**Issue by kibroutski** [hamishcunningham/pi-tronics#124]
Edit: posted too quickly....it was simply a poor soldering job causing
==============
Hi there, 

Just received my mopi 2 from Digital-Key and I have it working fine on a Raspberry 3 B+. Now when I  test it on my Pi Zero W (Buster lite / I2C enabled / same power supply) I have the following error.

> pi@raspberrypi:~ $ sudo mopi
> /usr/sbin/mopi: /usr/sbin/mopicli not working; installation problem? (mopicli. Remote I/O error)
> Usage: mopi [-h(elp)] [-d(ebug)] [-v(ersion)] [-l(og entries)]

I did look in the previous errors and tried the workaround suggested in Issue #110 with no success. The board does power the Pi without any issue, I simply cannot run mopi. 

Any suggestions ?

**Comment by hamishcunningham** [comment]
I guess you got it running...?
[Ah I see the changed title :)]

**Comment by kibroutski** [comment]
I'll try it tonight and update if it works fine on the Zero
It was late last night and I forgot the obvious check before posting the
issue

EDIT no re-open: Working like a charm now
