### ISSUE TITLE
Pi wont boot with MoPi plugged in anymore

### ISSUE THREAD

**Issue by mikecardwell** [hamishcunningham/pi-tronics#15]
Something ominous has started happening with my Pi. If the MoPi is plugged in when I turn it on, it says:

<pre>
sh: can't access tty: job control turned off
/ #
</pre>

And drops me at a shell. So I unplugged it from my model B+ Pi which is running Noobs/Raspbian, and plugged it into my model B Pi which is running Raspbmc. That also fails at boot time, but in a completely different manner:

<pre>
Waiting for root device /dev/mmcblk0p2
mmc0: new high speed SDHC card at address 0007
mmcblk0: mmc0:0007 SD8GB 7.42 GiB
 mmcblk0: p1 p2
Indeed it is in host mode hptr0 = 00021501
VFS: Cannot open root device "mmcblk0p2" or unknown-block(179,2): error -19
Please append a correct "root=" boot option; here are the available partitions:
b300 7782400 mmcblk0 driver: mmcblk
b301 34816 mmcblk0p1 000f06a6-01
b302 7746560 mmcblk0p2 000f06a6-02
kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(179,2)
</pre>

I know that suggests something wrong with the storage, but as soon as I unplug the MoPi from the GPIO pins on either Pi, everything boots up fine... It's almost as though it's mistaking the MoPi for storage and trying to use it that way. None of the LEDs light up on it anymore.

Any ideas?

**Comment by hamishcunningham** [comment]
IIRR you figured this one out in the end so closing... feel free to reopen if needed!
