### ISSUE TITLE
Mopi on a 12v lead acid

### ISSUE THREAD

**Issue by MTBHuw** [hamishcunningham/pi-tronics#21]
Hi, before I plug everything in, can the Mopi be connected up to a 12v lead acid battery?! Thanks.

**Comment by wayner9** [comment]
I am using a sealed lead acid battery.  What do I enter for cell configuration?  I have put in six cells - is that correct?

**Comment by hamishcunningham** [comment]
I think each cell is 2V when full -- so if you've a 12V battery then it is
probably 6 cells, but a 6V battery is prob 3...
hth
h

On 29 January 2015 at 20:48, wayner9 <notifications@github.com> wrote:

> I am using a sealed lead acid battery. What do I enter for cell
> configuration? I have put in six cells - is that correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/21#issuecomment-72101169>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  http://twitter.com/@HCunningham  hamish@gate.ac.uk
http://pi.gate.ac.uk    http://hamish.gate.ac.uk   http://gate.ac.uk
