### ISSUE TITLE
Automatic on?

### ISSUE THREAD

**Issue by basak** [hamishcunningham/pi-tronics#22]
Hi,

I'm looking for a solution to powering a Pi in a car. I have two 12V power sources available: one that's always on and connected to the battery, and one that's only on when the ignition is turned on.

Since the Pi will eventually drain the car battery, I'd like the Pi to be able to detect and shut itself down safely after the ignition is turned off (or choose to continue running for a certain length of time; the point is that the Pi would be in control of this). As far as I can tell, the MoPi will let me arrange this.

I also need the Pi to be automatically powered back on from this shutdown state when ignition power is restored. So I'd like to nominate one of the two power sources for the MoPi to treat as a signal to power on when edge-triggered from low to high.

There's also the race condition to consider when the Pi has just shut down but has yet to signal the MoPi to shut off, and the ignition is turned back on at this time.

I can't find any reference to the MoPi having the power on behaviour I need. But it seems to me that this is something the MoPi hardware should be able to do. Is the microcontroller source code available anywhere, please? I'm interested in modifying it if required.

**Comment by hamishcunningham** [comment]
Apologies for the sluggish reply; hopefully this would help:
https://pi.gate.ac.uk/posts/2015/02/11/in-car-mopi/

**Comment by basak** [comment]
Thanks. I ended up doing this with my own latching circuit and without MoPi. Since a separate circuit is needed anyway and the car battery 12V can be treated as always available, I didn't see a need for it. I'll write about my solution soon.
