### ISSUE TITLE
RPi + MoPi + 12v + 12vAmplifier + Recharchable = portable mopidy Boombox

### ISSUE THREAD

**Issue by zenonasz** [hamishcunningham/pi-tronics#24]
Hi
considering the diagram at https://pi.gate.ac.uk/pages/mopi.html#section-9.1
So, let me clarify the purpose;
The project is a portable RPi mopidy boombox. There is an RPi with a MoPi, a 12v battery and a 12v amplifier to power the speakers. 

The ideal scenario is to power the RPi and the amplifier from the battery and when a power source plugs in, charge the battery and power the RPi and the amplifier.

Considering the diagram https://pi.gate.ac.uk/pages/mopi.html#section-9.1 I did some modification in order achieve the ideal scenario above. My concerns are many, since I am really new to electronics, I would really appreciate if you had a look. 

I do believe there’s more research for me in order to achieve the above goal, but you might point me to the right direction.

Regards from sunny Cyprus,
Zenon.
![circuit](https://cloud.githubusercontent.com/assets/4558968/5009836/463af81c-6a74-11e4-9405-3667a4fe6beb.png)

**Comment by blackstarek** [comment]
@zenonasz I know its closed issue, but did you make any progress :)?
