### ISSUE TITLE
FYI - PiBoatMon - Mopi powered boat monitoring

### ISSUE THREAD

**Issue by gregcope** [hamishcunningham/pi-tronics#26]
HI,

Just thought I would share a little project I have been working on that uses the MoPI to run, monitoring and timer based power on to remote monitor a boat.

Thanks Hamish.

https://github.com/gregcope/piboatmon

**Comment by hamishcunningham** [comment]
hi Greg, appy noo yer an all :-)

Sorry for forgetting that was you -- great project! I've just corrupted an SD too; what is Puppet? My mate Gareth is using read-only images -- similar thing?

Cheers,

H

**Comment by gregcope** [comment]
Hi,

Np about mixing me up.

Not puppet to blame - just random power off.  Done it again since.  What is odd is that it seems to affect files that are only used at start up (in my case /etc/init.d/checkroot.sh and /etc/default/rcS) which is odd as these are not written to.

Gently building up the puppet module to turn an OOB raspbian image to RO, with a /home dir mounted RW on a new partition.  Using puppet.  Check my github.  So far have /boot RO, and getting to point I can have / RO too.
