### ISSUE TITLE
raspberry Pi with Mopi and 8 NiMh rechargeable batteries

### ISSUE THREAD

**Issue by mopiuser** [hamishcunningham/pi-tronics#29]
Hello, 

I just got my Mopi and tried to power my raspberry Pi, first I try with a 9 V Nimh rechargeable battery, the pi was only connected to internet for all the tests, no monitor nor any other pheriperal are attached. After around 5 minutes the Pi just suspend itself automatically due to not enough power supply. Then as recommended I switch the power supply to a power-pack of 8 AA 1.2 V 2500 mAh batteries changing the mopi setting to configuration 2 (by removing the small plastic slot in the mopi). The batteries I have used where previously fully loaded for around 7 hours from a new package. Unfortunately this second time the results where the same, after almost the same amount of time, the Pi suspended again automatically. 

Looking in internet about the duration time with such a battery pack, people speak about 8 hours, which in face of my results seems to indicate that I am making something wrong or the mopi is not working properly.

Could anyone please let me know what can I do to solve the problem? I have reviewed the connections, they seems to be Ok, comparing with the documentation. What can I test to identify the problem? the batteries are, after the 5 minutes, almost completely discharged. It seems like the Mopi is doing a good job discharging the batteries almost inmediately. 

Please let me know what can I do to identify the problem.  

Thank you

**Comment by hamishcunningham** [comment]
Hi!

> I just got my Mopi and tried to power my raspberry Pi, first
> I try with a 9 V Nimh rechargeable battery, the pi was only
> connected to internet for all the tests, no monitor nor any
> other pheriperal are attached. After around 5 minutes the Pi
> just suspend itself automatically due to not enough power
> supply. Then as recommended I switch the power supply to a
> power-pack of 8 AA 1.2 V 2500 mAh batteries changing the
> mopi setting to configuration 2 (by removing the small
> plastic slot in the mopi). The batteries I have used where
> previously fully loaded for around 7 hours from a new
> package. Unfortunately this second time the results where
> the same, after almost the same amount of time, the Pi
> suspended again automatically.

The 2600 mAh NiMH AAs that we've been using take around 11
hours to charge.

Re. the quick shutdown, you could try checking the config by
logging into the Pi and running "mopi".

It is likely that there is a problem with the battery charge
one way or another. It might also be worth checking the
quality and condition of the battery holders and associated
wiring, as this can vary quite a lot.

> Looking in internet about the duration time with such a
> battery pack, people speak about 8 hours, which in face of
> my results seems to indicate that I am making something
> wrong or the mopi is not working properly.

You can see lots of test results here:
https://pi.gate.ac.uk/pages/mopi.html#detailed-testing

> Could anyone please let me know what can I do to solve the
> problem? I have reviewed the connections, they seems to be
> Ok, comparing with the documentation. What can I test to
> identify the problem? the batteries are, after the 5
> minutes, almost completely discharged. It seems like the
> Mopi is doing a good job discharging the batteries almost
> inmediately.

The "mopi" tool and also the "mopicli" command-line version
are good places to start. Note that you can run the Pi powered
via a 5V USB connection while checking out what MoPi is doing
if you're having problems with shutdowns...

HTH, best

Hamish
