### ISSUE TITLE
Is there a MoPi equivalent for SFF Intel PCs?

### ISSUE THREAD

**Issue by wayner9** [hamishcunningham/pi-tronics#30]
There are some applications where I would want to use a PC more powerful than a Raspberry Pi.  One interesting alternative is the Small Form Factor PCs coming out these days like a Zotac Pico PC or an Intel NUC.  

I would like to use this type of box as a Car PC running a media server like Plex or Kodi - but there is the issue of power management.  Essentially I need something like a MoPi that would work to power an Intel PC that could manage power when the "mains" power supply is cut and would allow a clean shutdown.  

Does anyone know if such a product exists?  I guess I would want it to act like the DC power supply to this type of PC.

**Comment by hamishcunningham** [comment]
Not that I know of; we could build one for you :-)
Best, H
