### ISSUE TITLE
Does MoPi read voltages less than 6.2V?

### ISSUE THREAD

**Issue by wayner9** [hamishcunningham/pi-tronics#31]
I am playing around with some solar cells and when I connected a 3V solar cell to MoPi it didn't appear able to read it.  I know 6.2V is the minimum voltage to power the pi, but is that also the minimum voltage that can be read by the MoPi as well?

**Comment by hamishcunningham** [comment]
Yes, 6.2V is the operating floor of the unit itself. To cope with lower voltages either string a couple of panels in series -- e.g. https://pi.gate.ac.uk/posts/2014/08/03/solar-mopi/ -- or pick up a buck boost dc-dc converter.
