### ISSUE TITLE
By the way Model A+ works with MoPi

### ISSUE THREAD

**Issue by wayner9** [hamishcunningham/pi-tronics#34]
This might be obvious but the MoPi documentation mentions the Model A, Model B and Model B+.  It does not mention the Model A+ - I assume that is likely because the docs were written before the A+ existed.  I have been using my MoPi with the A+ and it works fine.

p.s. I guess there will soon be the Pi 2  Model B to add to the docs as well.

**Comment by hamishcunningham** [comment]
Thanks, I've added a note re. the A+. My Pi 2 is in the post!
