### ISSUE TITLE
device tree breaks I2c

### ISSUE THREAD

**Issue by achrn** [hamishcunningham/pi-tronics#36]
Device tree in new firmware means that I2C in the existing software for Mopi does not work.  Furthermore, the error at install time that would tell you this gets overlooked (by me at least) because the web page says "you will get a warning message; just ignore it at this point!"  You do get a warning message, and it's very similar but not quite the same as the warning message you should ignore.

Anyhow, I don't know if this is easily fixed in the software to configure the I2C automagically, but it's easy to fix by manual intervention when you know how:

sudo raspi-config

select 'advanced options'

select 'I2c' and say you do want to enable the I2C interface, and you do want to load the module

Then everything works.  Adding this sequence to the troubleshooting section on the web site would be good.  Putting something against the 'you'll get a warning message just ignore it' section would help too.

**Comment by hamishcunningham** [comment]
hi,

Thanks for this!

Are you running a B+ or...? I haven't seen this error as yet -- though RPI.GPIO seems to be broken on the Model 2 which scuppers things :-(

(As Ben said, why didn't they give developers some warning?!)

cheers

h

**Comment by achrn** [comment]
Yes, 'just' a B+, though one with a bleeding-edge 'sudo raspi-config', so I don't think it's an issue yet in the less exciting apt-get update / apt-get upgrade cycle.

It's nothing to do with the Pi2-breaks-gpio issues.

**Comment by hamishcunningham** [comment]
ok, tnx, will try and duplicate

On 9 February 2015 at 21:53, achrn <notifications@github.com> wrote:

> Yes, 'just' a B+, though one with a bleeding-edge 'sudo raspi-config', so
> I don't think it's an issue yet in the less exciting apt-get update /
> apt-get upgrade cycle.
>
> It's nothing to do with the Pi2-breaks-gpio issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/36#issuecomment-73598250>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  http://twitter.com/@HCunningham  hamish@gate.ac.uk
http://pi.gate.ac.uk    http://hamish.gate.ac.uk   http://gate.ac.uk

**Comment by jdotbdot** [comment]
I get the same issue with models B and B+.

MoPi works on a freshly installed system using 2014-12-24-wheezy-raspbian.img
It stops working after apt-get update and apt-get upgrade

It is fixed by re-enabling I2C in raspi-config.

**Comment by hamishcunningham** [comment]
I have fixed this and made a new release (4.1) to the PPA -- if you get a chance to try it out that would be great :-)

Now updating the docs...

Thanks for the heads-up, sorry it took me a while (I haven't rebuilt the package since last June, and it is a bit of a complex beast...).

**Comment by jdotbdot** [comment]
Thanks for the quick response Hamish.

Unfortunately I can't test it because I have fried my MoPi by means of a
loose wire and short circuit.

I guess it's all part of the learning process!

Kind regards,
jb

**Comment by hamishcunningham** [comment]
:-(

worth checking if it is just the fuse? (which should autoreset after a min
or two if not totally fritzed)

h

On 18 February 2015 at 17:18, jdotbdot <notifications@github.com> wrote:

> Thanks for the quick response Hamish.
>
> Unfortunately I can't test it because I have fried my MoPi by means of a
> loose wire and short circuit.
>
> I guess it's all part of the learning process!
>
> Kind regards,
> jb
>
> On 17 February 2015 at 17:26, Hamish Cunningham <notifications@github.com>
> wrote:
>
> > I have fixed this and made a new release (4.1) to the PPA -- if you get a
> > chance to try it out that would be great :-)
> >
> > Now updating the docs...
> >
> > Thanks for the heads-up, sorry it took me a while (I haven't rebuilt the
> > package since last June, and it is a bit of a complex beast...).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/hamishcunningham/pi-tronics/issues/36#issuecomment-74710128
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/36#issuecomment-74905503>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  http://twitter.com/@HCunningham  hamish@gate.ac.uk
http://pi.gate.ac.uk    http://hamish.gate.ac.uk   http://gate.ac.uk

**Comment by achrn** [comment]
Hi Hamish.  Thanks for the update.  Slight delay because my 'spare' pi was running a 3-day timelapse gathering process.  I obviously need a spare spare.

Anyhow, update is now in wherever it needs to be because I wrote a new flash card from the image that previously failed and after a new apt-get upgrade 30 minutes ago it all works first time with no problems.

**Comment by hamishcunningham** [comment]
grand, thanks!
best
h

On 19 February 2015 at 19:50, achrn <notifications@github.com> wrote:

> Hi Hamish. Thanks for the update. Slight delay because my 'spare' pi was
> running a 3-day timelapse gathering process. I obviously need a spare spare.
>
> Anyhow, update is now in wherever it needs to be because I wrote a new
> flash card from the image that previously failed and after a new apt-get
> upgrade 30 minutes ago it all works first time with no problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/36#issuecomment-75122820>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  http://twitter.com/@HCunningham  hamish@gate.ac.uk
http://pi.gate.ac.uk    http://hamish.gate.ac.uk   http://gate.ac.uk
