### ISSUE TITLE
MoPi discussion forum

### ISSUE THREAD

**Issue by wayner9** [hamishcunningham/pi-tronics#44]
Is there a place to discuss MoPi applications, projects, etc?  I have posted stuff on this site on Github before but often I am not raising technical issues, and would be more suitable to a discussion forum than a code repository.

**Comment by hamishcunningham** [comment]
raising an issue on the github repo is best at present
tnx
h

On 18 June 2015 at 20:26, wayner9 <notifications@github.com> wrote:

> Is there a place to discuss MoPi applications, projects, etc? I have
> posted stuff on this site on Github before but often I am not raising
> technical issues, and would be more suitable to a discussion forum than a
> code repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/44>.
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  https://twitter.com/@HCunningham  hamish@gate.ac.uk
https://pi.gate.ac.uk    https://hamish.gate.ac.uk   https://gate.ac.uk
