### ISSUE TITLE
Mopi current limit ?

### ISSUE THREAD

**Issue by binky72** [hamishcunningham/pi-tronics#45]
I am using the mopi to act as a ups for a RPi2 that I use in my car as a PLEX media server.
For storage I'm using an external hdd which is working fine when the USB power of the RPi2 is increased to 1.2A (max_usb_current=1) and the RPi2 is powered through the miniusb and a 2.1A 5V usb car charger. However, I would also like to power the RPi2 through the mopi board together with the battery backup. But when I try to power up the RPi2 with the 12V supply from my car through the mopi board it seems that RPi2 and the USB ports is not getting the same amp compared to when the RPi2 is powered through the miniusb. Reason for this is that the external hdd do not spin up and therefore not working. Is there a amp limit through the mopi? Do I have to change something in the mopi configuration to increase the current, e.g. in the same way as max_usb_current=1?

**Comment by hamishcunningham** [comment]
hi, in this issue we discussed high current usage: https://github.com/hamishcunningham/pi-tronics/issues/23

you're probably just on the borderline :-(

MoPi will supply an amp at least, but it does look like your HDD is not getting enough juice. the only thing I can suggest is

- make sure all the wiring is secure and of adequate size
- try the circuit linked to my reply to the previous issue

hth, best

h
