### ISSUE TITLE
Mopi and B+

### ISSUE THREAD

**Issue by david1944** [hamishcunningham/pi-tronics#47]
I now have two (2) B+ boards that demonstrate the same problems.  The only, repeat only, board that has been attached to both is MOPI.  The fault generated by using Mopi within its rules are a non-functioning set of usb ports and lan port.  The only time during my trials of mopi have either been attached to mains supply was to fill out the configuration on command line. Mopi worked with the first board intermittently and with the second board only once and then although it booted Raspberry it failed to get as far as login; it loaded simbamon and then reset itself and stopped at the rainbow screen.  There was no message to show what had cause it to stop; hey, and guess what I can't log in or connect to the internet brcause the usb/lan ports are not working.  I have just finished trying to get a result using a serial connection, but, although I can get one to boot to login I cannot use my keyboard or that of the connecting Debian PC. Passive connection through putty doesn't even give me a login or password entry.  Has anyone suffered the same fate?  Hamish, if you or your team have any ideas for a solution then please let me know quickly.

**Comment by hamishcunningham** [comment]
hi David

The only thing that I can think of is that you're connecting batteries that have insufficient charge to persuade MoPi to power the Pi.

There are a range of problems that you might be hitting with the Pi itself -- have you tried a new OS, for example, in relation to the USB problems? At some point the older versions of Raspbian suffered from this problem with the B+ IIRR. Perhaps you might remove MoPi from the equation and pursue these problems separately on the Pi forum? 

It seems quite unlikely that you're the first to hit some new fundamental problem -- there are around 1000 boards out there which are working nicely :-)

So I would recommend:

- removing MoPi and powering from the mains
- reflashing your SD card with a new OS
- when you're back up and running trying MoPi again, but paying particular attention
  to config and battery charge and the like

Hope this helps, best,

Hamish

**Comment by david1944** [comment]
Hello again Hamish,Thanks for your prompt response, but I have tried all of your suggestions before I reported the issue.  With the USB and LAN ports out of action It matters not whether the right noobs is or has been applied.  If you can't attach a keyboard or mouse then you cannot use a re-flashed card at all.  Mopi is the only link that I can see clearly   As a last resort I thought that using a PC to boot raspi from the serial port was worth a try, but the same thing happened - without a keyboard I cannot instruct (interact with) raspi. to use minicom or even to use recovery shift - but then the LAN's absence would stop the reloading of raspbian. I did wonder if, with your knowledge and academic status you could suggest a more unique  and bespoke answer; a script that could be fed into the recovery command line perhaps. because my windows PC can open the sdhc card and with notepad++ can edit the file. I have a PC that runs debian ; it has python.  Its HDD is 160gb and only a couple of weeks old. Can that be used?  I am in your hands so to speak.  If you can help i would appreciate it.Hope to hear from you soon,All the best,David. 

Date: Thu, 30 Jul 2015 08:19:35 -0700

**Comment by hamishcunningham** [comment]
It is worth reflashing anyhow as that may fix thr usb prob， which is prob
software not hardware?

**Comment by david1944** [comment]
Date: Thu, 30 Jul 2015 08:19:35 -0700

**Comment by hamishcunningham** [comment]
I have had a USB malfunction on a Pi before -- I know what it is like :-)

In my case, taking out the SD card, putting it in another machine and
reflashing a newer OS cured the problem.
Have you tried that?

If not, why are you convinced that the USB problem is a hardware fault?
Thanks, best, H

On 1 August 2015 at 11:49, david1944 <notifications@github.com> wrote:

>
>
> Date: Thu, 30 Jul 2015 08:19:35 -0700
> From: notifications@github.com
> To: pi-tronics@noreply.github.com
> CC: puddle247@hotmail.co.uk
> Subject: Re: [pi-tronics] Mopi and B+ (#47)
>
>
> Dear Hamish, Sorry to put you to the trouble of having to read fully my
> statement and then to give a coherent and considered response. There is a
> simplicity about my rasp[i problem which you have failed to grasp. That
> is:- Without USB and LAN ports you cannot a) use recovery command line,
> and, b) you cannot connect to the interrnet. I still feel that the problem
> is a hardware one. So how do I find a workaround. More of that later. I
> have 12 x 9v0 batteries. Before I contacted you I did the following
> exercise, Each battery had a sticker with a letter A<B<C< etc and each was
> measured by my multimeter before being used and that value written on the
> label. I then connected pairs of batteries to Mopi and noted the results.
> The voltages ranged from 9.74 to 7.35. One pair showed a result; batteries
> G an I - with
> a combined voltage of 16.31 volts showed a steady blue on mopi and Pi had
> a steady red and a flickering green. It did not boot pi. Took G off and all
> dead. Took mopi off and re-loaded the batteries and this time all dead.
> Measured the output an it haDn't varied greatly. Took I of and replaced it
> with D and the combined volage was 17.14 ;result red on mopi flashed but
> didn't light pi. Then tried G&I again and dead.hi David.
> And you say pay particular attention to batteries. Yesterday I recharged
> four NiMH batteries and tried them without a result. I then took Mopi off
> and booted via mains, Mopicli still not in evidence. No login - no usb
> keyboard. Bought a new usb keyboard and usb mouse; no difference no usb. I
> put I then changed the card for a boot into X gui. No mouse control. Then
> put adafruit resistive touchscreen tft on board to allow me to read the
> boot record as it loaded. Found one usb which with further reading and
> applied logic was the micro-port, which was obviously working.
> Now back to solutions. Firstly sales of 1000 with only my issue being
> raised is a return of 1:100 or a 0.0021 failure rate. Quality standards is
> good but a 1 in a 1000 is not unexpected even if small batches were tested
> before sale. This one could still have slipped through the net.
> I have tried to use my RS232 module but I cannot get an internet ip[ or a
> reply from Raspi - no keyboard. I can load the sdhc into Debian but the
> files I need to change are not editable without raspi's root login. It is
> this area that I need help with. I simply believe if the fault is software
> then software can correct it. I have six sdhc's ready and one which I noo
> bed some days ago which I cannot boot. So you see my logic is reasoned.
> Please read all of my messages before responding.
> Best,
> David.
>
>
>
>
> .hi David.
> The only thing that I can think of is that you're connecting batteries
> that have insufficient charge to persuade MoPi to power the Pi.
>
>
> There are a range of problems that you might be hitting with the Pi itself
> -- have you tried a new OS, for example, in relation to the USB problems?
> At some point the older versions of Raspbian suffered from this problem
> with the B+ IIRR. Perhaps you might remove MoPi from the equation and
> pursue these problems separately on the Pi forum?
>
>
> It seems quite unlikely that you're the first to hit some new fundamental
> problem -- there are around 1000 boards out there which are working nicely
> :-)
>
>
> So I would recommend:
>
>
>
> removing MoPi and powering from the mains
> reflashing your SD card with a new OS
> when you're back up and running trying MoPi again, but paying particular
> attention
> to config and battery charge and the like
>
>
> Hope this helps, best,
>
>
> Hamish
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/47#issuecomment-126897665>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  https://twitter.com/@HCunningham  hamish@gate.ac.uk
https://pi.gate.ac.uk    https://hamish.gate.ac.uk   https://gate.ac.uk
