### ISSUE TITLE
Switch / bypass

### ISSUE THREAD

**Issue by andybill5129** [hamishcunningham/pi-tronics#48]
Is there a way to bypass the switch, so that the Pi boots immediately when power applied, and also starts up when power re-applied?

**Comment by hamishcunningham** [comment]
not directly -- this does something like that:
https://www.circuitlab.com/circuit/shevrt/in-car-mopi/

On 13 August 2015 at 13:21, andybill5129 <notifications@github.com> wrote:

> Is there a way to bypass the switch, so that the Pi boots immediately when
> power applied, and also starts up when power re-applied?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/48>.
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  https://twitter.com/@HCunningham  hamish@gate.ac.uk
https://pi.gate.ac.uk    https://hamish.gate.ac.uk   https://gate.ac.uk
