### ISSUE TITLE
Persistent WON and WSD values?

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#49]
Hi there;

Doing some testing with the MoPi, and was wondering if the values set for WON and WSD are persistent, or if they need to be set every time the RPi starts up again?  I set the WON and WSD values while the RPi was on, and it shut down down and powered back up as expected, but that was it, it didn't shut down a second time.  Thanks!

**Comment by hamishcunningham** [comment]
IIRR the battery config is persisted (on the Pi, then pushed to MoPi on
each startup), but I don't think WON and WSD are. I think we envisaged this
as a step that was taken once per runtime, not something with a repeat
facility.

On 16 August 2015 at 19:24, James Eberhardt <notifications@github.com>
wrote:

> Hi there;
>
> Doing some testing with the MoPi, and was wondering if the values set for
> WON and WSD are persistent, or if they need to be set every time the RPi
> starts up again? I set the WON and WSD values while the RPi was on, and it
> shut down down and powered back up as expected, but that was it, it didn't
> shut down a second time. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/49>.
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  https://twitter.com/@HCunningham  hamish@gate.ac.uk
https://pi.gate.ac.uk    https://hamish.gate.ac.uk   https://gate.ac.uk
