### ISSUE TITLE
Display current schedule?

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#50]
Is there anything that will allow me to display the current schedule for the next WSD and WON events?  It would be good to see when the RPi will next shut down and start up.

Thanks.

**Comment by hamishcunningham** [comment]
Fred reminds me that:

mopicli -rsd -ron

will read back the current values of the shutdown and poweron timers.

See https://pi.gate.ac.uk/pages/mopi.html#section-4.3.
