### ISSUE TITLE
Header Pins for Remote Switch

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#51]
Thanks for leaving the solder pads for a remote switch, it's very useful.  Is there any way they could be header pins?  That way it would be easy to attach / detach a remote switch.

**Comment by hamishcunningham** [comment]
Nice idea James, but we don't actually have a header of our own :-(   I'll mention it to Lubo though, who is designing the next iteration of the board. Cheers, H

**Comment by hamishcunningham** [comment]
Lubo says: "In the new version we have possibilities to extend the LEDs also. With some defined by us types, due to the differences in currents. All are as soldering paths now, but will put small header at the end if the space permits."
