### ISSUE TITLE
Remote Status Lights

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#52]
I see there are a few status lights on the board.  One for indicating that the board is starting up or shutting down, and some others that flash yellow when the batteries are low.  Is there any way to extend these lights (much like the remote power switch)?  I will be enclosing the RPi in a case, and would like to be able to see these lights on the outside of the case.

**Comment by hamishcunningham** [comment]
Sorry, no, you'll have to unsolder them :-(

On 16 August 2015 at 21:24, James Eberhardt <notifications@github.com>
wrote:

> I see there are a few status lights on the board. One for indicating that
> the board is starting up or shutting down, and some others that flash
> yellow when the batteries are low. Is there any way to extend these lights
> (much like the remote power switch)? I will be enclosing the RPi in a case,
> and would like to be able to see these lights on the outside of the case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/52>.
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  https://twitter.com/@HCunningham  hamish@gate.ac.uk
https://pi.gate.ac.uk    https://hamish.gate.ac.uk   https://gate.ac.uk
