### ISSUE TITLE
Real-time clock?

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#61]
I need to attach a real-time clock to my RPi, and was wondering if there was any type of Real-time clock capability that exists in the MoPi that I could leverage.  Since it has the ability to start the RPi at a specific time, I was thinking something might be there.

Thanks for any input.

**Comment by hamishcunningham** [comment]
Tis there but not accessible:-(

**Comment by jeberhardt** [comment]
That's too bad it's not accessible.  It would have been great to use that to set the time on the RPi if a network connection wasn't available.

**Comment by ravjots** [comment]
Needed same functionality so added ds3231 on stackable model and that worked

**Comment by hamishcunningham** [comment]
Makes sense, thanks!
