### ISSUE TITLE
Dont want the leds to waste battery during sleep time.

### ISSUE THREAD

**Issue by ravjots** [hamishcunningham/pi-tronics#62]
Hi,

When we use the sleep functionalily the mopi shutsdown raspberry pi but the LEDs stay on, these leds discharge the batteries so i want to switch them on during sleep. Is this possible?

Regards,
Ravjot

**Comment by hamishcunningham** [comment]
This would require firmware mods which are not currently supported :-(
h

On 6 October 2015 at 14:01, ravjots <notifications@github.com> wrote:

> Hi,
>
> When we use the sleep functionalily the mopi shutsdown raspberry pi but
> the LEDs stay on, these leds discharge the batteries so i want to switch
> them on during sleep. Is this possible?
>
> Regards,
> Ravjot
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/62>.
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  https://twitter.com/@HCunningham  hamish@gate.ac.uk
https://pi.gate.ac.uk    https://hamish.gate.ac.uk   https://gate.ac.uk
