### ISSUE TITLE
Charging Circuit with MoPI

### ISSUE THREAD

**Issue by ginzer** [hamishcunningham/pi-tronics#66]
Hey  I want to have a Raspberry working with a rechargable Battery and a power supply. When I plug in the power supply battery should be charged and when the battery is full charging should stop and the raspi should work with the power supply. When I plug off the ower supply Raspi should work with the Battery.  Something like that. But i dont really get it. is U4 conected to the MoPi supply 2 or to the USB supply from the PI?
![upsconfig](https://cloud.githubusercontent.com/assets/16148261/11584768/0e42f918-9a67-11e5-8e21-f61a8aa473be.png)

The other one i found here shoul work......
![lipocharger](https://cloud.githubusercontent.com/assets/16148261/11584912/52484626-9a68-11e5-896e-77df68376d5d.png)
or am I wrong? I just dont need the amplifier and stuff....

Thanks for any help.

**Comment by hamishcunningham** [comment]
howdy

looking back at the first (UPS) circuit (where U4 is a bog standard 5V supply connected to the micro USB on the Pi) it relies on the 5V supply overpowering the supply from MoPi... 

but yes, the second circuit sounds more like what you need; just delete U3 (and, if you like, specify a lower current 12V supply, or 9V supply, for U2).

hth, best,
h

**Comment by ginzer** [comment]
thanks. and the system wont shut down because the relais is to slow?

**Comment by hamishcunningham** [comment]
not in similar circuits I've built before, but YMMV :-)

a mosfet would do the job just as well, though you don't get the cute
clicking noise :-)

hf
h

On 4 December 2015 at 11:27, ginzer <notifications@github.com> wrote:

> thanks. and the system wont shut down because the relais is to slow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/66#issuecomment-161943173>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk       *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

**Comment by ginzer** [comment]
thanks a lot.

**Comment by blackstarek** [comment]
Howdy, @ginzer , any progress? I just bought mopi and i miss this function, how did you succeed?

**Comment by ginzer** [comment]
hey....no no progress. I just decided to use a Powerbank wit pass-through function.

**Comment by blackstarek** [comment]
@ginzer may i ask you which powerbank did you use and how did you connect it?

**Comment by ginzer** [comment]
its a limefuel. I just connected it to the power supply of the raspy

**Comment by ginzer** [comment]
but to be honest the i would prefer the solution with the mopi.
@hamishcunningham is there any current limitation for the mopi? My Raspberry needs arround 2A.

**Comment by hamishcunningham** [comment]
2A is the max output :-)
h

On 22 January 2016 at 08:08, ginzer <notifications@github.com> wrote:

> but to be honest the i would prefer the solution with the mopi.
> @hamishcunningham <https://github.com/hamishcunningham> is there any
> current limitation for the mopi? My Raspberry needs arround 2A.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/66#issuecomment-173839125>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk       *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

**Comment by ginzer** [comment]
ok thanks :-). perfect

so I could make it like that talking about shematic 2):

instead of the 220V supply I use a 5V supply which gets to the Lipo charger and to the Mopi.... and if I take away the supply the battery will supply the Mopi (and the Raspi.....)

**Comment by hamishcunningham** [comment]
MoPi requires a 6.2V min supply voltage, and it is typically easier to
arrange things with a higher voltage, e.g. 12V

hth

h

On 22 January 2016 at 09:09, ginzer <notifications@github.com> wrote:

> ok thanks :-). perfect
>
> so I could make it like that talking about shematic 2):
>
> instead of the 220V supply I use a 5V supply which gets to the Lipo
> charger and to the Mopi.... and if I take away the supply the battery will
> supply the Mopi (and the Raspi.....)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/66#issuecomment-173855035>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk       *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

**Comment by ginzer** [comment]
ok. so if I use a 12V supply it should work.
