### ISSUE TITLE
Questions before buying for Carputer

### ISSUE THREAD

**Issue by Queonda1** [hamishcunningham/pi-tronics#67]
Hello,  Please excuse me if this is the wrong place to ask the question.

Going to build a carputer with the Raspberry Pi 2, and looking at the MoPi.  From the Car MoPi circuit (https://pi.gate.ac.uk/images/mopi/in-car.png);  Is RP1 and RP2 in the diagram remote switch?

Nice users guide, lots of reading but I'm still unclear of the following:

The unit doesn't automatically power on the Raspberry Pi when power is supplied to S1?
Is there a time limit I can program, when S1 drops?  Let's say stay on for 20 minutes if on S2 then do controlled shutdown?

I've been seeing linux love, what about Android?  Will I be able to do a shutdown with android with MoPi?

**Comment by hamishcunningham** [comment]
hi!

Going to build a carputer with the Raspberry Pi 2, and looking at the MoPi
> From the Car MoPi circuit (https://pigateacuk/images/mopi/in-carpng); Is
> RP1 and RP2 in the diagram remote switch?
>

yes, as here: https://pi.gate.ac.uk/posts/2014/07/10/mopi-remote-switch/

> Nice users guide, lots of reading but I'm still unclear of the following:
>
> The unit doesn't automatically power on the Raspberry Pi when power is
> supplied to S1?
>
no, there is no auto-on -- hence the relays in the car circuit IIRR


> Is there a time limit I can program, when S1 drops? Let's say stay on for
> 20 minutes if on S2 then do controlled shutdown?
>
you can monitor voltage on the Pi, and do a shutdown when you prefer


> I've been seeing linux love, what about Android? Will I be able to do a
> shutdown with android with MoPi?
>
no android support -- but feel free to add it :-)


have a good one,
h
