### ISSUE TITLE
Send Power to USB hub.

### ISSUE THREAD

**Issue by JamesEberhardt** [hamishcunningham/pi-tronics#69]
I'm using a Raspberry Pi Zero with a Mopi. The WiFi dongle via the USB hub needs external power since the RPi Zero won't power it. I'd like to use the same set of batteries to power both the RPi Zero and the USB hub. Is there a way to route the power from the MoPi to the USB hub?

Thanks!

**Comment by hamishcunningham** [comment]
you can take a feed from the 5v pin on the gpio header (or where the header would be if you soldered one on). all you have to watch out for is not to exceed overall current limits, but with just a zero and a wifi dongle that should be fine

**Comment by JamesEberhardt** [comment]
What is the "overall current limits"?

**Comment by hamishcunningham** [comment]
2A as stated in the docs ;-)

On 4 January 2016 at 15:32, JamesEberhardt <notifications@github.com> wrote:

> What is the "overall current limits"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/69#issuecomment-168707549>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk       *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham
