### ISSUE TITLE
MoPi power sources flash then nothing.

### ISSUE THREAD

**Issue by swojtowicz** [hamishcunningham/pi-tronics#72]
Hi, my MoPi was working fine.  Suddenly when I try to turn it on, the 2 power source LED's flash a few times then go out and nothing else happens and it won't turn on.  I checked the voltage out from my 2 power supplies (9v's) and they both are about about 7.8 volts.  Is there any meaning behind the flashing LED's?

Thanks!

**Comment by hamishcunningham** [comment]
perhaps the 9v supplies are dipping under load?
it sounds like there is insufficient voltage to persuade mopi to start -- that could also be a config error; did you config simbamond for your supply characteristics?
hth
h

**Comment by swojtowicz** [comment]
Aahhh I'm dumb.  It was the batteries.  As soon as you said they might be dipping "under load", I went and picked up more 9v's (had no spares to try when I first posted my issue).  I should have tried that first.  Thank you!

**Comment by hamishcunningham** [comment]
Cool, have a good one!
