### ISSUE TITLE
MoPi, erratic power behavior even with fully charged batteries

### ISSUE THREAD

**Issue by binky72** [hamishcunningham/pi-tronics#73]
I have a MoPi powering my mobile RPI2 in my car (as a Plex server). The main power source is the 12V from the car with a 7.2V LiPo (6.6 Ah) as backup. In the beginning everything work perfect, very stable. But a couple of months ago the MoPi started to have an erratic behavior. The MoPI unit seems to have some issue with the connect power sources. Even with fully charged LiPo and also connected to the 12V car output with a steady blue RGB led both amper leds starts to blink. After some time the unit will then shutdown. Sometimes only one amper led is blinking (usually the LiPo amper led), resulting in a shutdown when I stop the car. This will also happen when it's only powered with LiPo (both blue and green RGB led), and has also happened with the MoPi only powered by the 12V car output.

Any clues what could be wrong?

Regards
Eirik

**Comment by hamishcunningham** [comment]
hi Eirik

sorry to hear you're having problems; have you tried measuring the voltages on the source lines into MoPi? and checking that the configuration is appropriate for your setup? 7.2 is at the low end; if you have the default config that will appear to be an empty battery...

hth,
h
