### ISSUE TITLE
dead mopi

### ISSUE THREAD

**Issue by gituseraccount** [hamishcunningham/pi-tronics#77]
My mopi is not working correctly. I bought it from buyapi They redirected me to contact you. I'm not very good . Programming I don't see what's wrong. I just need the mobile power.

**Comment by hamishcunningham** [comment]
pls detail what you did, and what "not working" means. thanks!

**Comment by gituseraccount** [comment]
Simply does not work ie: no power no voltage , current and resistance with volt meter

Sent from my BlackBerry 10 smartphone.
From: Hamish Cunningham
Sent: Friday, April 1, 2016 5:15 PM
To: hamishcunningham/pi-tronics
Reply To: hamishcunningham/pi-tronics
Cc: gituseraccount
Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)



pls detail what you did, and what "not working" means. thanks!

-

**Comment by hamishcunningham** [comment]
how did you connect it? how did you configure it? what batteries did you
connect? did any lights come on? did they flash?
tnx
h

On 1 April 2016 at 22:17, gituseraccount <notifications@github.com> wrote:

> Simply does not work ie: no power no voltage , current and resistance with
> volt meter
>
> Sent from my BlackBerry 10 smartphone.
> From: Hamish Cunningham
> Sent: Friday, April 1, 2016 5:15 PM
> To: hamishcunningham/pi-tronics
> Reply To: hamishcunningham/pi-tronics
> Cc: gituseraccount
> Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)
>
>
>
> pls detail what you did, and what "not working" means. thanks!
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204567762
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204568187>
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk       *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

**Comment by gituseraccount** [comment]
Through the power sockets. Used this guide http://projects-raspberry.com/mopi-is-mobile-hot-swap-and-247-power-for-the-raspberry-pi/ A Put it with a 3.72000mah - 5volt battery with 3000ma. Also tried other batteries so it's not that for sure and it's not the raspberry pi 3.

Sent from my BlackBerry 10 smartphone.
From: Hamish Cunningham
Sent: Friday, April 1, 2016 6:24 PM
To: hamishcunningham/pi-tronics
Reply To: hamishcunningham/pi-tronics
Cc: gituseraccount
Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)


how did you connect it? how did you configure it? what batteries did you
connect? did any lights come on? did they flash?
tnx
h

On 1 April 2016 at 22:17, gituseraccount <notifications@github.com> wrote:

> Simply does not work ie: no power no voltage , current and resistance with
> volt meter
>
> Sent from my BlackBerry 10 smartphone.
> From: Hamish Cunningham
> Sent: Friday, April 1, 2016 5:15 PM
> To: hamishcunningham/pi-tronics
> Reply To: hamishcunningham/pi-tronics
> Cc: gituseraccount
> Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)
>
>
>
> pls detail what you did, and what "not working" means. thanks!
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204567762
> >
>
> -
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204568187>
>



--

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk https://twitter.com/@HCunningham
https://hamish.gate.ac.uk *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

-

**Comment by hamishcunningham** [comment]
MoPi requires at least 6.2V to run. Try connecting a 12V battery for
example.

See e.g. https://pi.gate.ac.uk/pages/mopi.html#section-2.3.

HTH, best
Hamish

On 1 April 2016 at 23:45, gituseraccount <notifications@github.com> wrote:

> Through the power sockets. Used this guide
> http://projects-raspberry.com/mopi-is-mobile-hot-swap-and-247-power-for-the-raspberry-pi/
> A Put it with a 3.72000mah - 5volt battery with 3000ma. Also tried other
> batteries so it's not that for sure and it's not the raspberry pi 3.
>
> Sent from my BlackBerry 10 smartphone.
> From: Hamish Cunningham
> Sent: Friday, April 1, 2016 6:24 PM
> To: hamishcunningham/pi-tronics
> Reply To: hamishcunningham/pi-tronics
> Cc: gituseraccount
> Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)
>
>
> how did you connect it? how did you configure it? what batteries did you
> connect? did any lights come on? did they flash?
> tnx
> h
>
> On 1 April 2016 at 22:17, gituseraccount <notifications@github.com> wrote:
>
> > Simply does not work ie: no power no voltage , current and resistance
> with
> > volt meter
> >
> > Sent from my BlackBerry 10 smartphone.
> > From: Hamish Cunningham
> > Sent: Friday, April 1, 2016 5:15 PM
> > To: hamishcunningham/pi-tronics
> > Reply To: hamishcunningham/pi-tronics
> > Cc: gituseraccount
> > Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)
> >
> >
> >
> > pls detail what you did, and what "not working" means. thanks!
> >
> > -
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub<
> >
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204567762
> > >
> >
> > -
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204568187
> >
> >
>
>
>
> --
>
> *Hamish Cunningham*
> Professor of Computer Science, University of Sheffield, UK
> +44 7920 765 455
> hamish@gate.ac.uk https://twitter.com/@HCunningham
> https://hamish.gate.ac.uk *http://aquaponicslab.org/
> <http://aquaponicslab.org/>*
> https://gate.ac.uk https://pi.gate.ac.uk
> http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204592185
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204597211>
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk       *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

**Comment by gituseraccount** [comment]
still doesn't work
Sent from my BlackBerry 10 smartphone.
From: Hamish Cunningham
Sent: Saturday, April 2, 2016 7:14 AM
To: hamishcunningham/pi-tronics
Reply To: hamishcunningham/pi-tronics
Cc: gituseraccount
Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)


MoPi requires at least 6.2V to run. Try connecting a 12V battery for
example.

See e.g. https://pi.gate.ac.uk/pages/mopi.html#section-2.3.

HTH, best
Hamish

On 1 April 2016 at 23:45, gituseraccount <notifications@github.com> wrote:

> Through the power sockets. Used this guide
> http://projects-raspberry.com/mopi-is-mobile-hot-swap-and-247-power-for-the-raspberry-pi/
> A Put it with a 3.72000mah - 5volt battery with 3000ma. Also tried other
> batteries so it's not that for sure and it's not the raspberry pi 3.
>
> Sent from my BlackBerry 10 smartphone.
> From: Hamish Cunningham
> Sent: Friday, April 1, 2016 6:24 PM
> To: hamishcunningham/pi-tronics
> Reply To: hamishcunningham/pi-tronics
> Cc: gituseraccount
> Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)
>
>
> how did you connect it? how did you configure it? what batteries did you
> connect? did any lights come on? did they flash?
> tnx
> h
>
> On 1 April 2016 at 22:17, gituseraccount <notifications@github.com> wrote:
>
> > Simply does not work ie: no power no voltage , current and resistance
> with
> > volt meter
> >
> > Sent from my BlackBerry 10 smartphone.
> > From: Hamish Cunningham
> > Sent: Friday, April 1, 2016 5:15 PM
> > To: hamishcunningham/pi-tronics
> > Reply To: hamishcunningham/pi-tronics
> > Cc: gituseraccount
> > Subject: Re: [hamishcunningham/pi-tronics] dead mopi (#77)
> >
> >
> >
> > pls detail what you did, and what "not working" means. thanks!
> >
> > -
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub<
> >
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204567762
> > >
> >
> > -
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204568187
> >
> >
>
>
>
> --
>
> *Hamish Cunningham*
> Professor of Computer Science, University of Sheffield, UK
> +44 7920 765 455
> hamish@gate.ac.uk https://twitter.com/@HCunningham
> https://hamish.gate.ac.uk *http://aquaponicslab.org/
> <http://aquaponicslab.org/>*
> https://gate.ac.uk https://pi.gate.ac.uk
> http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204592185
> >
>
> -
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/77#issuecomment-204597211>
>



--

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455
hamish@gate.ac.uk https://twitter.com/@HCunningham
https://hamish.gate.ac.uk *http://aquaponicslab.org/
<http://aquaponicslab.org/>*
https://gate.ac.uk https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham

-

**Comment by gituseraccount** [comment]
Ya if you can send replacement
I send it back
106 niagara  st unit 2
St catharines
Ontario
Canada
L2r4l4

Sent from my BlackBerry 10 smartphone.
