### ISSUE TITLE
Feature Request: Standoff Connection.

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#80]
I was thinking that if the PCB extended just a little bit to the "top" of the board (the edge where the SD card is), there could be a hole that would allow a standoff to be inserted, allowing the MoPi to be solidly connected to the main board.  As it is now, there is a little bit of give to the MoPi, and I'm thinking that can't be a good thing.  Just a thought for your next revision.

**Comment by hamishcunningham** [comment]
Thanks! I'll pass it on to Lubo....
