### ISSUE TITLE
Mopi to supply power to USB Devices

### ISSUE THREAD

**Issue by jeberhardt** [hamishcunningham/pi-tronics#84]
One common problem is that the Raspberry Pi often needs a powered hub when connecting some USB devices.

I was wondering if there was any way to supply the power to the USB hub from the Mopi.  This would allow the battery connected to the Mopi to supply power to a powered USB hub without going through the Raspberry Pi itself (which would limit the draw).  Ideally, the power to the USB hub would be shut off and get turned on when the Mopi turns off / on the Raspberry Pi.

Thanks!

**Comment by hamishcunningham** [comment]
in theory yes, but in practise you may end up drawing too much current from
mopi :-(

On 23 June 2016 at 16:12, James Eberhardt <notifications@github.com> wrote:

> One common problem is that the Raspberry Pi often needs a powered hub when
> connecting some USB devices.
>
> I was wondering if there was any way to supply the power to the USB hub
> from the Mopi. This would allow the battery connected to the Mopi to supply
> power to a powered USB hub without going through the Raspberry Pi itself
> (which would limit the draw). Ideally, the power to the USB hub would be
> shut off and get turned on when the Mopi turns off / on the Raspberry Pi.
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hamishcunningham/pi-tronics/issues/84>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AEMQlNM1aZFoGSMqMn9IqQ3DZTuM4mb6ks5qOqJZgaJpZM4I86qo>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK

BBC Radio Sheffield say I'm a *fish poo boffin*
(http://www.bbc.co.uk/programmes/p03v9nyv 2 hours 37 mins in;
also on vid: http://bbc.in/20x2C5J & scroll down a little)

Phone: +44 7740 149 842
hamish@gate.ac.uk                 https://twitter.com/@HCunningham
https://hamish.gate.ac.uk           *https://wegrow.social
<https://wegrow.social/>*
https://gate.ac.uk                  https://pi.gate.ac.uk
http://www.dcs.shef.ac.uk/cgi-bin/makeperson?H.Cunningham
