### ISSUE TITLE
mopi turn on - turn off

### ISSUE THREAD

**Issue by fisholo** [hamishcunningham/pi-tronics#86]
Hi,
I recently buy a Mopi. Thanks for the good work. 

It's possible to use Mopi to power on and off Raspberry @ precise time? 

For example: I need to shoot photos @ 10 AM and @ 2 PM.

In order to minimize powe consumption I would like to turn on raspy @ 9.55 AM, off @ 10.05 AM and so on.. 

Thanks in advance for the answer. 

Fabrizio

**Comment by stoduk** [comment]
Hi,

[I'm just a user, nobody official!]  Yes, with caveats - see previous threads eg. #41 #70, ask if anything is not clear.

Cheers,
Anthony
