### ISSUE TITLE
mopi confuses I2C when connected to plug socket

### ISSUE THREAD

**Issue by CloudRike** [hamishcunningham/pi-tronics#87]
Hi everyone,

I have a mopi to power my RasPi outdoors with some different I2C sensors. When I connect a battery to mopi, everything works fine. But when I plug the Pi via MiniUSB to the plug socket, my Pi gets confused about I2C connections. Sometimes some addresses are not detected, sometimes the Pi displays all I2C addresses with i2cdetect. When I remove the mopi, or reconnect a battery, everything works fine again. I don't want to work on batteries, when I configure my Pi at home. So does anyone know the problem and can give me a hint how to solve it?

Thanks a lot for your replies!
Best wishes, Ulrike

**Comment by hamishcunningham** [comment]
Apologies for the slow reply! I have never seen this problem... do you still have it? Or found a solution?
Perhaps a noisy PSU?
Thanks, Hamish
