### ISSUE TITLE
Issue installing simbamond

### ISSUE THREAD

**Issue by Freelander12** [hamishcunningham/pi-tronics#89]
Hi 

Sorry if this is a silly question but I am having issues with installing simbamond on my RPi 2B.
I have installed this before on another SD card with no issues and found it easy to do, but on this image I can't seem to get it to install. The problem is when I run the command  "sudo apt-get install simbamond"_ I get the following issues which I have no idea how to fix. 

sudo apt-get install simbamond
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 simbamond : Depends: bc but it is not installable
E: Unable to correct problems, you have held broken packages.

I have run all the previous commands before this from the instructions with no issue (see below).

sudo apt-get update
sudo apt-get upgrade
sudo reboot
sudo rpi-update
sudo reboot

Any help would be appreciated.

Thanks Graham

**Comment by hamishcunningham** [comment]
sorry for slow reply :-(

I think you need to run that magic dpkg command that fixes broken dependencies... is it 

sudo dpkg --configure -a 

?

basically I think you have an inconsistent state in your apt package data...
