### ISSUE TITLE
MoPi usage considerations / questions

### ISSUE THREAD

**Issue by ssinfod** [hamishcunningham/pi-tronics#90]
Hello, I bought a MoPi for my RPI3. 
I have a few small questions regarding its usage.

The picture in the MoPi webpage (https://pi.gate.ac.uk/pages/mopi.html) shows two 8-AA batteries packs connected to the MoPi. This seems a lot of batteries (total of 16 AA batteries) and it is also big !

Here are my questions:

Q1) Can I use the MoPi like a UPS. That is using one input with permanent main power and the other input with a battery pack ? So, can I connect permanent power (Source #1) and only one battery pack (Source #2)?  

Q2) Considering that I only want to use the battery for automatic shutdown if the event of main power lost.
What is the minimum number of AA battery that I should use in the battery pack ? (I have a RPI3)
Can I use a 9 Volts battery ?
Even better, can I use a supercap instead of a battery / battery pack ?

Q3) Want would happen if the power is coming back in and back out and the battery pack is not fully charged / empty.
Does the MoPi check for minimum stable power before restarting the RPI ?  (ex: 1 minutes of stable power?)
Does the MoPi check for minimum voltage in the battery pack before restarting the RPI ? (ie: Does it wait that the battery is recharged before starting the RPI) ?

Thanks for your time,
ssinfod

**Comment by hamishcunningham** [comment]
hi

yes, you can connect a single 5v supply which *should* (depending on the supply) overpower the battery. this can either be to the Pi micro usb or to MoPi.
https://www.circuitlab.com/workbench/ has some designs for various more sophisticated UPS configurations... 

so it sounds like you should connect the permanent supply to mopi, and monitor via daemon. then power to run through to shut down depends on: peripherals and load on the Pi; speed of the daemon in picking up power drop. 9V PP3 batteries tend to drain v quickly, but *might* work

there's no auto-restart, and no built-in charging -- check the circuits above for options

cheers

h
