### ISSUE TITLE
auto shutdown

### ISSUE THREAD

**Issue by gigaguy** [hamishcunningham/pi-tronics#93]
I have my rpi3 running on USB power.  When that power drops, I want the mopi to take over and immediately shut it down (maybe wait 10sec or something).  I've tried setting the -wsd value, but that doesnt seem to do anything. It seems like its all dependent upon battery voltage remaining.  I just want a clean shutdown should main power drop.  How can I configure this?

**Comment by jeberhardt** [comment]
Have you tried setting it for a longer value? Like 1 minute? Precisely how are you trying to set the wsd value? I've had great success in getting it to work from the python library. Also, how are you detecting that the main power dropped?
