### ISSUE TITLE
Voltage displaying on raspberry pi 3

### ISSUE THREAD

**Issue by cpp5126** [hamishcunningham/pi-tronics#95]
currently, I am working on a project that uses Mopi to communicate and charge the Raspberry pi 3. I have trouble displaying the voltage on raspberry pi without using its buit-in api. Is there any other way we can display voltage on raspbery pi by ruuning a single python script to access the voltage data.

**Comment by hamishcunningham** [comment]
Hi, the command-line API should supply you with voltage data?

Note: we aren't supporting MoPi wth the Pi 3 now :-( 
See https://pi.gate.ac.uk/posts/2016/12/19/good-news-and-bad/ for details.

Best, Hamish

**Comment by ronisegoly** [comment]
I just saw that Mopi does not support RPI3 
I have also RPI2 I will test with
When will you support RPPI3
