### ISSUE TITLE
MOPI as UPS

### ISSUE THREAD

**Issue by ronisegoly** [hamishcunningham/pi-tronics#99]
Can I use it to MOPI to shutdown only when main power (USB) is down? How do you detect it.

**Comment by hamishcunningham** [comment]
Hi Roni, Perhaps this answers your question? https://pi.gate.ac.uk/pages/mopi.html#section-4.3.

I.e. run the mopicli script to see what the voltage on the different inputs is, and then shutdown as required.

HTH, Hamish

**Comment by ronisegoly** [comment]
Could you explain what you meant?
Can I detect if main power  (USB) is available? I did not see how to do it
Unless you meant running on two two sources on MOPI,
